# Старая версия `version` не нужна, как подсказал Docker, можно убрать
# version: '3.8' 

services:
  app:
    build: .
    container_name: digital_forest_app
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    # --- ДОБАВЛЕНО ---
    # Указываем, что этот сервис должен быть подключен к нашей кастомной сети
    networks:
      - digital_forest_net

  postgres:
    image: postgres:15-alpine
    container_name: digital_forest_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    # --- ДОБАВЛЕНО ---
    # Этот сервис тоже подключаем к той же сети
    networks:
      - digital_forest_net

volumes:
  postgres-data:

# --- ДОБАВЛЕН ЦЕЛЫЙ БЛОК ---
# Здесь мы описываем нашу кастомную сеть
networks:
  digital_forest_net:
    driver: bridge # Стандартный драйвер для создания виртуальной сети
    ipam: # IP Address Management - управление IP-адресами
      driver: default
      config:
        - subnet: 172.25.0.0/24 # Явно задаем подсеть. 
                               # Мы выбрали диапазон, который вряд ли с чем-то конфликтует