-- +goose Up
-- +goose StatementBegin
INSERT INTO plants (author, image_data) VALUES
('Alice', 'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAJ0lEQVQYV2N8+vTpfwYGBgYgFibKz89n2LhxYyA2kGViYtKABgA2kAlA+f889QAAAABJRU5ErkJggg=='),
('Bob', 'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAHElEQVQYV2N8DwQMFADG8GCwASwSoA3wAwCaVgEw428xNQAAAABJRU5ErkJggg=='),
('Charlie', 'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAJklEQVQYV2NkgID/gP4g5sV/kDgBmEUSkGViYuJ/gBT8gSkFAJU7B2c/G0kHAAAAAElFTSuQmCC');

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
TRUNCATE TABLE plants RESTART IDENTITY;
-- +goose StatementEnd
